name: Auto-merge when PR was approved
on:
  workflow_run:
    workflows: ["Notify when PR was approved"]
    brances: [develop]
    types:
      - completed
jobs:
  printJob:
    name: Print event
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: |
          echo "$GITHUB_CONTEXT"

  auto-merge-to-develop :
    if: github.event.workflow_run.conclusion == 'success'
    runs-on: ubuntu-latest
    steps:
      - name: Find second approve comment
        id: find-last-comment
        uses: peter-evans/find-comment@v1
        with:
          issue-number: ${{ github.run_number }}
          comment-author: 'github-actions[bot]'
          body-includes: 'Все аппрувы получены!'

      - name: Auto merge
        run: |
          echo ${{ secrets.GH }}
          echo ${{ secrets.GH }} > secret.txt
          gh auth login --with-token < secret.txt
          gh pr merge ${{ github.event.workflow_run.head_branch }} -s

      - name: GitHub Bot comment
        uses: peter-evans/create-or-update-comment@v1
        with:
          issue-number: ${{ github.run_number }}
          body: Автомёрдж ${{ github.event.workflow_run.head_branch }} в develop