name: Notify when PR was opened
on:
  pull_request:
    types: [ opened ]
jobs:
  opened:
    if: github.event.pull_request.base.ref == 'develop' || github.event.pull_request.base.ref == 'release'
    runs-on: ubuntu-latest
    steps:
      - name: Send Telegram message
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: |
            ${{ github.event.sender.login }} открыл ПР(#${{ github.event.number }}): «${{ github.event.pull_request.title }}» !

            Что изменилось?
            «${{ github.event.pull_request.body }}»

            Узнать больше: ${{ github.event.pull_request.html_url }}